# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/repo/SOC/SoC_301/2_GROUND_WORK/2_PS_BASIC/1_USART_CONNECTION_HW/1_USART_CONNECTION_HW.srcs/sources_1/bd/USART_HW/ip/USART_HW_processing_system7_0_0/USART_HW_processing_system7_0_0.xci
# IP: The module: 'USART_HW_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/repo/SOC/SoC_301/2_GROUND_WORK/2_PS_BASIC/1_USART_CONNECTION_HW/1_USART_CONNECTION_HW.gen/sources_1/bd/USART_HW/ip/USART_HW_processing_system7_0_0/USART_HW_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'USART_HW_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/repo/SOC/SoC_301/2_GROUND_WORK/2_PS_BASIC/1_USART_CONNECTION_HW/1_USART_CONNECTION_HW.srcs/sources_1/bd/USART_HW/ip/USART_HW_processing_system7_0_0/USART_HW_processing_system7_0_0.xci
# IP: The module: 'USART_HW_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/repo/SOC/SoC_301/2_GROUND_WORK/2_PS_BASIC/1_USART_CONNECTION_HW/1_USART_CONNECTION_HW.gen/sources_1/bd/USART_HW/ip/USART_HW_processing_system7_0_0/USART_HW_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'USART_HW_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
