# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/USART_HW/USART_HW.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==USART_HW || ORIG_REF_NAME==USART_HW} -quiet] -quiet

# IP: bd/USART_HW/ip/USART_HW_processing_system7_0_0/USART_HW_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==USART_HW_processing_system7_0_0 || ORIG_REF_NAME==USART_HW_processing_system7_0_0} -quiet] -quiet

# XDC: c:/repo/SOC/SoC_301/2_GROUND_WORK/2_PS_BASIC/1_USART_CONNECTION_HW/1_USART_CONNECTION_HW.gen/sources_1/bd/USART_HW/USART_HW_ooc.xdc
